services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - payments_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payments"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:root@db:5432/payments
      PAYMENT_GATEWAY_URL: http://mock-gateway:8001/mock-gateway
      TRANSACTION_FEE: 2
      AUTO_CREATE_TABLES: "true"
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
      CELERY_TASK_TIME_LIMIT_SECONDS: 30
      CELERY_TASK_SOFT_TIME_LIMIT_SECONDS: 25
      GATEWAY_TIMEOUT_SECONDS: 1.0
      GATEWAY_MAX_ATTEMPTS: 3
      GATEWAY_BACKOFF_BASE_SECONDS: 1.0
      GATEWAY_BACKOFF_MAX_SECONDS: 30.0
      GATEWAY_BACKOFF_JITTER_SECONDS: 0.5
      WORKER_POLL_INTERVAL_SECONDS: 0.5
      WORKER_PROCESSING_TIMEOUT_SECONDS: 30.0
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8000"

  worker:
    build: .
    command: ["celery", "-A", "app.workers.celery_app.celery_app", "worker", "--loglevel=INFO"]
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:root@db:5432/payments
      PAYMENT_GATEWAY_URL: http://mock-gateway:8001/mock-gateway
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
      CELERY_TASK_TIME_LIMIT_SECONDS: 30
      CELERY_TASK_SOFT_TIME_LIMIT_SECONDS: 25
      GATEWAY_TIMEOUT_SECONDS: 1.0
      GATEWAY_MAX_ATTEMPTS: 3
      GATEWAY_BACKOFF_BASE_SECONDS: 1.0
      GATEWAY_BACKOFF_MAX_SECONDS: 30.0
      GATEWAY_BACKOFF_JITTER_SECONDS: 0.5
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mock-gateway:
    build: .
    environment:
      GATEWAY_TIMEOUT_SECONDS: 1.0
    command: ["uvicorn", "app.mock_gateway_app:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  payments_db:
